# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvLHpKBbf3VoALDfJAGhBpwyjuqzzJJW
"""

import streamlit as st
import pandas as pd
from utils.optimizer import optimize_budget

# ---------------------------
# 1) LOAD DATA
# ---------------------------
@st.cache_data
def load_data():
    return pd.read_csv("data/final_investment_table.csv")

df = load_data()

st.title("OECD Budget Optimizer 🇮🇹")
st.write("Allocazione ottimale del budget per colmare i deficit negli indicatori OECD delle regioni italiane.")

# Check population column exists
if "Population" not in df.columns:
    st.error("❌ ERROR: 'Population' column is missing in `final_investment_table.csv`")
    st.stop()

# ---------------------------
# 2) UI INPUT
# ---------------------------
regioni = sorted(df["Region"].unique())
regioni_sel = st.multiselect("Seleziona una o più regioni (o lascia vuoto per tutte)", regioni)

budget = st.number_input(
    "Budget totale disponibile (€)",
    min_value=1000.0,
    value=1000000.0,
    step=100000.0
)

# ---------------------------
# 3) RUN OPTIMIZATION
# ---------------------------
if st.button("🚀 Ottimizza budget"):
    results = optimize_budget(df, budget, regioni_sel)
    st.subheader("🔍 Risultati dell’allocazione")
    st.dataframe(results)

    # key metrics
    total_initial = results["Initial Gap"].sum()
    total_final = results["Residual Gap"].sum()
    st.metric("📉 Gap iniziale totale", f"{total_initial:.2f}")
    st.metric("📉 Gap residuo totale", f"{total_final:.2f}")
    st.metric("🔥 Gap ridotto", f"{total_initial - total_final:.2f}")
    st.metric("💰 Budget residuo", f"{results['Remaining Budget'].iloc[-1]:.2f} €")

    # charts
    st.subheader("📊 Allocazione per indicatore")
    st.bar_chart(results.set_index("OECD Type")["Allocated Budget"])

    st.subheader("📉 Gap prima vs dopo")
    gap_compare = results.set_index("OECD Type")[["Initial Gap", "Residual Gap"]]
    st.bar_chart(gap_compare)

# footer
st.caption("Model prototype — greedy algorithm with total-cost scaling based on population")