# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hP0aU8he270pjBZ-exdgjPXrJWEDtjEi
"""

import streamlit as st
import pandas as pd
from utils.optimizer import optimize_budget   # import from utils/

@st.cache_data
def load_data():
    return pd.read_csv("data/final_investment_table.csv")

df = load_data()

st.title("OECD Budget Optimizer 🇮🇹")
st.write("Dai regioni + budget, ritorna allocazione ottimale per ridurre il gap negli indicatori OECD.")

# Input UI
regioni = sorted(df["Region"].unique())
regioni_sel = st.multiselect("Seleziona regioni (opzionale)", regioni)

budget = st.number_input("Budget totale", value=1000000.0, step=100000.0)

if st.button("Ottimizza"):
    results = optimize_budget(df, budget, regioni_sel)
    st.dataframe(results)

    # Metriche finali
    st.write("---")
    total_initial = results["Initial Gap"].sum()
    total_final = results["Residual Gap"].sum()
    st.metric("Gap Iniciale Totale", f"{total_initial:.2f}")
    st.metric("Gap Residuo Totale", f"{total_final:.2f}")
    st.metric("Gap Ridotto", f"{total_initial - total_final:.2f}")

    # Grafici
    st.bar_chart(results.set_index("OECD Type")["Allocated Budget"])
    st.bar_chart(results.set_index("OECD Type")[["Initial Gap", "Residual Gap"]])

st.caption("Prototype version — greedy algorithm")