# -*- coding: utf-8 -*-
"""optimizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZE4OkCpRof6ijBDVyw_qmXDGx12fEtc-
"""

import pandas as pd

def optimize_budget(final_investment_table, total_budget, target_regions=None):
    df_opt = final_investment_table.copy()
    if target_regions and len(target_regions) > 0:
        df_opt = df_opt[df_opt['Region'].isin(target_regions)]

    df_opt = df_opt.sort_values(by='CostPerPoint', ascending=True).reset_index(drop=True)

    remaining_budget = total_budget
    allocations, gap_reductions, residual_gaps, initial_gaps = [], [], [], []

    for idx, row in df_opt.iterrows():
        initial_gap = row["Gap"]
        cost_per_point = row["CostPerPoint"]
        max_investment_needed = initial_gap * cost_per_point
        actual_investment = min(remaining_budget, max_investment_needed)

        remaining_budget -= actual_investment
        gap_reduction = actual_investment / cost_per_point if cost_per_point else 0
        current_residual_gap = max(0, initial_gap - gap_reduction)

        allocations.append(actual_investment)
        gap_reductions.append(gap_reduction)
        residual_gaps.append(current_residual_gap)
        initial_gaps.append(initial_gap)

        if remaining_budget <= 0:
            break

    num_allocated = len(allocations)
    if num_allocated < len(df_opt):
        allocations.extend([0]*(len(df_opt) - num_allocated))
        gap_reductions.extend([0]*(len(df_opt) - num_allocated))
        residual_gaps.extend(df_opt["Gap"].iloc[num_allocated:].tolist())
        initial_gaps.extend(df_opt["Gap"].iloc[num_allocated:].tolist())

    df_res = df_opt.copy()
    df_res["Initial Gap"] = initial_gaps
    df_res["Allocated Budget"] = allocations
    df_res["Gap Reduction"] = gap_reductions
    df_res["Residual Gap"] = residual_gaps
    df_res["Remaining Budget"] = remaining_budget

    return df_res

